version: '3'
services:
   web:
      build: ./docker
      restart: always
      env_file:
         - ./.env
      environment:
         - WEB_ALIAS_DOMAIN=${MAGENTO_URL_HOST}
         - PHP_DISPLAY_ERRORS=1
         - PHP_MEMORY_LIMIT=756M
         - PHP_MAX_EXECUTION_TIME=300
         - PHP_POST_MAX_SIZE=2048M
         - PHP_UPLOAD_MAX_FILESIZE=1024M
         - XDEBUG_REMOTE_AUTOSTART=0
         - XDEBUG_REMOTE_PORT=10000
         - XDEBUG_PROFILER_ENABLE=0
         - XDEBUG_REMOTE_CONNECT_BACK=0
         - XDEBUG_REMOTE_HOST=${MAGENTO_URL_HOST}
         - PHP_OPCACHE_MAX_ACCELERATED_FILES=100000
         - PHP_OPCACHE_MEMORY_CONSUMPTION=512
         - PHP_OPCACHE_REVALIDATE_FREQ=5
         - PHP_OPCACHE_INTERNED_STRINGS_BUFFER=32
         - php.xdebug.idekey=XDEBUG_VSCODE
         - php.xdebug.remote_enable=0
         - php.xdebug.max_nesting_level=1000
         - php.enable_dl=0
         - php.max_input_nesting_level=800
         - php.max_input_vars=100000
         - php.realpath_cache_ttl=600
         - php.short_open_tag=1
         - php.zend.assertions=-1
         - php.memcached.sess_connect_timeout=1000
         - php.memcached.sess_consistent_hash=0
         - php.session.gc_divisor=1000
         - php.session.gc_maxlifetime=86400
         - php.session.gc_probability=1
         - php.opcache.enable_file_override=1
         - php.opcache.fast_shutdown=0
         - php.opcache.optimization_level=0x7FFFBFFF
         - php.mysqli.reconnect=1
         - php.mysqli.allow_local_infile=1
         - php.apc.shm_size=128M
         - php.apc.enabled=0
         - FPM_PM_START_SERVERS=3
         - FPM_PM_MIN_SPARE_SERVERS=2
         - FPM_PM_MAX_SPARE_SERVERS=4
         - FPM_MAX_REQUESTS=200
         - fpm.global.emergency_restart_threshold=10
         - fpm.global.emergency_restart_interval=1m
         - fpm.global.process_control_timeout=10s
         - VIRTUAL_HOST=${MAGENTO_URL_HOST}
      volumes:
         - ./htdocs:/app:cached
         - ./.modman:/.modman:ro
      ports:
         - "${WEB_SERVER_PORT}:80"
         - "${WEB_SERVER_SECURE_PORT}:443"
         - 22
   mysql:
      image: percona/percona-server:5.6
      restart: always
      ports:
         - 3306
      environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=${DATABASE_NAME}
      volumes:
         - db-data:/var/lib/mysql
   phpmyadmin:
      restart: always
      image: phpmyadmin/phpmyadmin:latest
      environment:
         - PMA_HOST=${DATABASE_HOST}
         - MYSQL_ROOT_PASSWORD=root
         - PMA_USER=${DATABASE_USER}
         - PMA_PASSWORD=${DATABASE_PASSWORD}
         - PMA_PORT=3306
      ports:
         - 80
      depends_on:
         - mysql
volumes:
   db-data:
      external: false
